name: Discord Bot CI

on:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Build Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
          python -m pip install poetry

      - name: Install Poetry Dependencies
        shell: bash
        run: python -m poetry install

      - name: Test with pytest
        run: |
          python -m poetry run pytest .

      - name: Run tox
        run: tox
